#+title: README for dotzshrc

A git repository for managing my =.zshrc= configuration.

Below is the top-level directory structure:

#+BEGIN_SRC
├── License
├── README.org
├── RUNBOOK.org
├── bin
├── configs
├── install.rb
├── iterm
├── runbooks
├── stylesheets
└── symlinks
#+END_SRC

- License :: the license associated with this repository
- README.org :: this file
- RUNBOOK.org :: this is the software/scripts I install to ensure I have the appropirate dependencies installed.
- bin :: a directory of executable files
- configs :: a directory containing shell configs
- install.rb :: this creates the symlinks in my =$HOME= directory and ensures paths, aliases, etc. are correct in the terminal/shell.
- iterm :: iterm configurations along with keymappings for running Emacs in shell (not recommended)
- runbooks :: varioius runbooks for different situations I’ve encountered
- stylesheets :: a directory wiith =userContent.css=; a stylesheet for adding to a browser’s default stylesheets
- symlinks :: a directory containing the various files that I symblink into my =$HOME= directory.

You can run =ruby install.rb= to create the symlinks into the current =$HOME= file

*Note:* [[https://github.com/jeremyf/dotzshrc][My dotzshrc repository]] assumes that you also have a clone of [[https://github.com/jeremyf/dotemacs][my dotemacs repository]] in the same parent directory.
