#+title: README for dotzshrc

A git repository for managing my =.zshrc= configuration.

Below is the top-level directory structure:

#+BEGIN_SRC
.
├── License
├── README.org
├── RUNBOOK.org
├── bin
├── configs
├── install.rb
├── iterm
├── karabiner
├── lib
├── runbooks
├── stylesheets
├── symlinks
└── todo.org
#+END_SRC

- License :: the license associated with this repository.
- README.org :: this file.
- RUNBOOK.org :: this is the software/scripts I install to ensure I have the appropirate dependencies installed; it is always a work in progress and one only vetted when I get a new machine.
- bin :: a directory of executable files.
- configs :: a directory containing shell configs.
- install.rb :: this creates the symlinks in my =$HOME= directory and ensures paths, aliases, etc. are correct in the terminal/shell.
- iterm :: iterm configurations along with keymappings for running Emacs in shell (not recommended).
- lib :: a place for weird one off scripts.
- runbooks :: varioius runbooks for different situations I’ve encountered.
- stylesheets :: a directory wiith =userContent.css=; a stylesheet for adding to a browser’s default stylesheets
- symlinks :: a directory containing the various files that I symblink into my =$HOME= directory.
- todo.org :: my todo items for this repository.

You can run =ruby install.rb= to create the symlinks into the current =$HOME= file

*Note:* [[https://github.com/jeremyf/dotzshrc][My dotzshrc repository]] assumes that you also have a clone of [[https://github.com/jeremyf/dotemacs][my dotemacs repository]] in the same parent directory.
