#+title: Runbook for My OS X Setup

This is my hopefully complete Runbook for getting a new macOS computer running.

- Install homebrew :: https://brew.sh ; package manager
- Install OhMyZsh :: https://github.com/ohmyzsh/ohmyzsh ; zshell option
- Install Powerlevel10k :: https://github.com/romkatv/powerlevel10k
- Install Base16 Shell :: https://github.com/chriskempson/base16-shell
- Install ImageOptim :: https://imageoptim.com/ ; remove image metadata

- =brew install cmake= :: cross-platform make (may not be necessary with macOS only install)
- =brew tap homebrew/cask= :: make sure to get access to casks
- =brew install raycast= :: it’s +Spotlight+ Alfred replacement; a launcher and more.
- =brew install git= :: macOS git is always behind the times, this will help keep it updated.
- =brew install git-extras= :: some extra commands for git
- =brew install git-secrets= :: handle git secrets (e.g., keychain)
- =brew install hub= :: terminal integration with github

- =brew install openssl= :: You're going to want this for rbenv, though look at ./runbooks/ruby-openssl
- =brew install postgresql= :: postgresql database
- =brew install rbenv= :: Ruby version manager (we’ll install Ruby’s later)
- =brew install redis= :: Going to need this for asyn rails work

- =brew install ag= :: A solid replacement for grep
- =brew install ripgrep= :: Another solid replacement for grep that allows PERL Regexp
- =brew install terminal-notifier= :: Send macOS notifications from terminal
- =brew install fzf= :: Fuzzy finder
- =brew install bat= :: A cat clone with syntax highlighting
- =brew install pandoc= :: for converting documents to different formats

- =brew install appcleaner= :: for cleaning out applications and all their extra files

** Fonts

- Install MesloLGS NF via Powerlevel10k instructions
- Install JetBrains Mono font
- Install Ubuntu font https://design.ubuntu.com/font/
- =brew cask install font-hack-nerd-font=
- =brew tap homebrew/cask-fonts=
- =brew install font-iosevka-nerd-font=


** Emacs

The following is necessary for getting Emacs up and running

- =brew install libgit2= :: C-Library for Git that improves Emacs’s magit speed
- =brew install coreutils= :: GNU file, shell, and text utilities
- =brew install mactex= :: for LaTeX rendering (e.g., org mode exports)
- =ln -s $HB_PATH/bin/gls $HB_PATH/bin/ls= :: This addresses "/ERROR/: Listing directory failed but 'access-file' worked"

- =brew tap d12frosted/emacs-plus=
- =brew install emacs-plus@28 --with-debug --with-dbus --with-xwidgets --with-modern-pen-lds56-icon --with-native-comp=

*** Alternate

~brew install emacs-mac  --with-dbus --with-glib --with-imagemagick --with-jansson --with-libxml2 --with-rsvg  --with-mac-metal --with-native-comp --with-natural-title-bar --with-starter  --with-emacs-sexy-icon~

** Run ./install.rb

=ruby install.rb= to create various symlinks.

** SSH Keys

Ensure that I have up to date SSH keys

For Github, need to create a new app token

** Install Karabiner

https://karabiner-elements.pqrs.org/

Then set:

- Right option key to send ESC
- Caps lock to send CTRL
- Left shift + Right shift sends CAPS LOCK

** Install Hammerspoon

See [[https://github.com/Hammerspoon/hammerspoon][Hammerspoon/hammerspoon: Staggeringly powerful macOS desktop automation with Lua]].

** The Deprecated

Prior to Raycast, I used Jumpcut (=brew cask install jumpcut=)