ZSH_THEME="powerlevel9k/powerlevel9k"

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_COLOR_SCHEME='light'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(aws dir vcs rbenv)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time date time)
POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW=true
POWERLEVEL9K_DATE_FORMAT="%D{%Y-%M-%d}"
