;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        comment-line
        duplicate-line
        end-of-buffer
        fill-paragraph
        git-rebase-squash
        hungry-delete-backward
        hungry-delete-forward
        indent-for-tab-command
        magit-status
        markdown-outdent-or-delete
        mouse-set-region
        ns-copy-including-secondary
        ns-do-show-character-palette
        org-cycle
        org-metaright
        org-self-insert-command
        org-todo
        sp-backward-delete-char
        string-inflection-all-cycle
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        ivy-switch-buffer
        ))
