command_timeout = 1000

[directory]
truncation_length = 8
truncate_to_repo = false
truncation_symbol = './'

[gcloud]
format = "\non [$symbol$project in $region]($style) "

[git_branch]
style = 'bold green'
symbol = " "
truncation_length = 50
truncation_symbol = '…'

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = "([$all_status$ahead_behind]($style) )"
modified = '${count}󰇂 '
stashed = '${count}󰼜 '
untracked = '${count}? '
style = 'bold green'

[python]
symbol = '🐍 '
pyenv_version_name = true

[status]
disabled = false
